# Generated by Django 3.1.3 on 2020-11-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Введите номер игры', unique=True, verbose_name='Номер игры')),
                ('name', models.CharField(blank=True, help_text='Введите название игры', max_length=300, null=True, verbose_name='Название игры')),
                ('time', models.DateTimeField(blank=True, help_text='Введите дату и время игры', null=True, verbose_name='Дата и время игры')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_question', models.TextField(help_text='Введите вопрос', verbose_name='Вопрос')),
                ('correct_answer', models.CharField(help_text='Введите ответ', max_length=200, verbose_name='Ответ')),
                ('count_points', models.PositiveIntegerField(help_text='Введите количество очков', verbose_name='Количество очков')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='OwnGame.category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ForeignKey(help_text='Выберите игру', on_delete=django.db.models.deletion.CASCADE, to='OwnGame.game', verbose_name='Игра'),
        ),
    ]
